common/models/Book.php
<?php

namespace common\models;

use Yii;
use yii\helpers\Html;
use common\models\BookTenant;

/**
 * This is the model class for table "books".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $date
 * @property int $status
 */
class Book extends \yii\db\ActiveRecord
{
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'description', 'date', 'status'], 'required'],
            [['name', 'description'], 'string'],
            [['date'], 'safe'],
            [['status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'date' => 'Date',
            'status' => 'Status',
        ];
    }


    public function buttonAdmin($idLease){

        //$book = new Book();

        if(BookTenant::find()->where(['status' => 0])->andWhere(['id' => $idLease])->one()){
                    $button = Html::a('Выдать', ['book/issue', 'id' => $idLease], ['class' => 'btn btn-primary']);
                }elseif(BookTenant::find()->where(['status' => 1])->andWhere(['id' => $idLease ])->one()){
                    $button = Html::a('Вернуть', ['book/book_delete', 'id' => $idLease], ['class' => 'btn btn-danger']);
                }

        return $button;
    }
}

frontend/controllers/BookController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Book;
use common\models\BooksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\BookHistory;
use common\models\BookTenant;
use yii\filters\AccessControl;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],

                    ],
                    [
                        'actions' => ['view','occupy','my_books','cancel','list_book'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['logout','create','delete','update','lease','book_delete','issue','index','history'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $book = new Book();
        $bookTenant = new BookTenant();
        $description = BookTenant::find()->where(['user_id' => Yii::$app->user->identity->id])->andWhere(['book_id' => $id])->andWhere(['status' => 1])->all();
        return $this->render('view', [
            'model' => $this->findModel($id),
            'book' => $book,
            'bookTenant' => $bookTenant,
            'description' => $description,
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        $model->status = 1;
        $model->date = date('Y-m-d H:i:s');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            ]);
    }

/**
* Updates an existing Book model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
* @return mixed
* @throws NotFoundHttpException if the model cannot be found
*/
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionOccupy($id){
        
        $bookHistory = new BookHistory();
        $bookTenant = new BookTenant();

        $bookHistory->saveHistory0($id);
        $bookTenant->saveBook($id);

        return $this->redirect(['view','id' => $id]);
        
    }

    public function actionLease(){
        
        $book = new Book();
        
        $leases = BookTenant::find()->all();

        return $this->render('lease',[
            'leases' => $leases,
            'book' => $book,
        ]);
    }

    public function actionIssue($id){
        
        $bookHistory = new BookHistory();

        $model = BookTenant::findOne($id);
        $model->status = 1;
        $model->save();  // equivalent to $model->update();

        $idBook = $model;

        $bookHistory->saveHistory1($idBook);

        return $this->redirect(['lease']);
        
    }

    public function actionBook_delete($id){


        $bookHistory = new BookHistory();
        $model = BookTenant::findOne($id);
        $bookHistory->saveHistory2($model);
        
        $model = BookTenant::findOne($id)->delete();

        return $this->redirect(['lease']);
        
    }

    public function actionCancel($id){

        $idTenant = BookTenant::find()->where(['book_id' => $id])->andWhere(['user_id' => Yii::$app->user->identity->id])->one();

        $bookHistory = new BookHistory();
        $model = BookTenant::findOne($idTenant->id);
        $bookHistory->saveHistory3($model);
        
        $model = BookTenant::findOne($idTenant->id)->delete();

        return $this->redirect(['view','id' => $id]);
        
    }

    public function actionMy_books(){
        $book = new BookTenant();
        

        $leases = BookTenant::find()->where(['user_id' => Yii::$app->user->identity->id])->andWhere(['status' => 1])->all();

        return $this->render('myBooks',[
            'leases' => $leases,
            'book' => $book,
        ]);
    }

    public function actionList_book(){
        //$book = new BookTenant();

        $listB = Book::find()->all(); 
        return $this->render('listBook',[
            'listB' => $listB,
        ]);
    }

    public function actionHistory(){
        $history = BookHistory::find()->all();

        return $this->render('history',[
            'history' => $history,
        ]);
    }

}

frontend/views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textinput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\BooksSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/book/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Book */

$this->title = 'Create Book';
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/book/history.php
<table border="1">
   <caption>История книг</caption>
    <tr>
        <th style="width: 55px">Имя</th>
        <th style="width: 1050px">Книга</th>
        <th>История</th>
        <th style="width: 108px">Дата</th>
    </tr>
        <?php foreach ($history as $bookStory): ?>
        <tr>
            <td><?= $bookStory->user->username ?></td>
            <td><?= $bookStory->book->name ?></td>
            <td>
                <?php if($bookStory->status == 0): ?>
                    <?= "Запросил" ?>
                <?php elseif ($bookStory->status == 1): ?>
                    <?= "Админ разрешил" ?>
                <?php elseif ($bookStory->status == 2):?>
                    <?= "Админ взял обратно" ?>
                <?php elseif($bookStory->status == 3): ?>
                    <?= "Пользователь отменил заказ" ?>
                <?php endif; ?>
            </td>
            <td><?=$bookStory->datetime?></td>
        </tr>
        <?php endforeach; ?>
</table>

frontend/views/book/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\BooksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Books';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Book', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name:ntext',
            'date',
            'status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

frontend/views/book/lease.php
<?php

use Yii;
use yii\helpers\Url;
?>

<style type="text/css">
table {
font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
text-align: left;
border-collapse: separate;
border-spacing: 5px;
background: #ECE9E0;
color: #656665;
border: 16px solid #ECE9E0;
border-radius: 20px;
width: -moz-available;
}
th {
font-size: 18px;
padding: 10px;
}
td {
background: #F5D7BF;
padding: 10px;
}
</style>


<table>
   <caption>Заказы</caption>
<tr>
  <th>№</th>
   <th>Пользователь</th>
  <th colspan="1">Изображение</th>
  <th colspan="2">Название книг</th>
  <th></th>
</tr>
<?php  $i = 1; foreach ($leases as $lease): ?>
<tr>  
  <td><?= $i ?></td>
  <td><?= $lease->user->username ?></td>
  <td><img src="/images/index.png"></td>
  <td style="font-size: x-large;"><a href="<?= Url::toRoute(['book/view', 'id' => $lease->book->id]) ?>"><?= $lease->book->name ?></a></td>
  <?php $idLease = $lease->id; ?>
  <td><?= $book->buttonAdmin($idLease); ?></td>
</tr>
<?php $i++; endforeach; ?>
</table>

frontend/views/book/listBook.php
<?php

use Yii;
use yii\helpers\Url;
?>

<style type="text/css">
table {
font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
text-align: left;
border-collapse: separate;
border-spacing: 5px;
background: #ECE9E0;
color: #656665;
border: 16px solid #ECE9E0;
border-radius: 20px;
width: -moz-available;
}
th {
font-size: 18px;
padding: 10px;
}
td {
background: #F5D7BF;
padding: 10px;
}
</style>


<table>
   <caption>Книги</caption>
<tr>
  <th>№</th>
  <th colspan="1">Изображение</th>
  <th colspan="2">Название книг</th>
</tr>
<?php  $i = 1; foreach ($listB as $list): ?>
<tr>  
  <td><?= $i ?></td>
  <td><img src="/images/index.png"></td>
  <td style="font-size: x-large;"><a href="<?= Url::toRoute(['book/view', 'id' => $list->id]) ?>"><?= $list->name ?></a></td>
</tr>
<?php $i++; endforeach; ?>
</table>

frontend/views/book/myBooks.php
<?php

use Yii;
use yii\helpers\Url;
?>

<style type="text/css">
table {
font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
text-align: left;
border-collapse: separate;
border-spacing: 5px;
background: #ECE9E0;
color: #656665;
border: 16px solid #ECE9E0;
border-radius: 20px;
width: -moz-available;
}
th {
font-size: 18px;
padding: 10px;
}
td {
background: #F5D7BF;
padding: 10px;
}
</style>


<table>
   <caption>Мои книги</caption>
<tr>
  <th>№</th>
  <th colspan="1">Изображение</th>
  <th colspan="2">Название книг</th>
</tr>
<?php  $i = 1; foreach ($leases as $lease): ?>
<tr>  
  <td><?= $i ?></td>
  <td><img src="/images/index.png"></td>
  <td style="font-size: x-large;"><a href="<?= Url::toRoute(['book/view', 'id' => $lease->book->id]) ?>"><?= $lease->book->name ?></a></td>
</tr>
<?php $i++; endforeach; ?>
</table>

frontend/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Book */

$this->title = 'Update Book: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Book */

$this->title = $model->name;
$id = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="book-view">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <p>
        <?php if (Yii::$app->user->can('admin')): ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?php else: ?>
        
        <?= $bookTenant->button($id); ?>
    <?php endif ?>
    </p>

    <?php if(empty($description)): ?>
     <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name:ntext',
        ],
    ]) ?>
    <?php else: ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name:ntext',
            'description:ntext',
            'date',
            'status',
        ],
    ]) ?>
<?php endif ?>

</div>